### ISSUE TITLE
不能识别域名

### ISSUE THREAD

**Issue by chinaboy007** [liuymcn/rocketmq-exporter-go#7]
不能失败域名
docker run -it --rm -p 9999:9999 lucas987/rocketmq-exporter-go:v0.1.1 --rocketmq.nameserver="rocketmq-prod.ddplatform.svc.cluster.local:9876"
INFO[0000] Fly                                           listenAddress=":9999" metricsPath=/metrics opts="{[rocketmq-prod.ddplatform.svc.cluster.local:9876] 100}"
FATA[0000] create Exporter                               err="IP addr error"

**Comment by kirovcaptain** [comment]
使用域名的方式为
--rocketmq.nameserver.use.domain
--rocketmq.nameserver.domain="rocketmq-prod.ddplatform.svc.cluster.local" 
--rocketmq.nameserver.port=9876
